steps:
- name: 'bash'
  id: SubstituteVars
  args: ['./substitutevars.sh']
  env:
    - '_API_KEY=$_API_KEY'
    - '_AUTH_DOMAIN=$_AUTH_DOMAIN'
    - 'PROJECT_ID=$PROJECT_ID'
    - '_STORAGE_BUCKET=$_STORAGE_BUCKET'
    - '_MESSAGE_SENDER_ID=$_MESSAGE_SENDER_ID'
    - '_APP_ID=$_APP_ID'
- name: 'gcr.io/cloud-builders/yarn'
  id: Packages
  args: ['--cwd', 'src', 'install']
- name: 'gcr.io/cloud-builders/yarn'
  id: Build
  args: ['--cwd', 'src', 'build']
- name: 'gcr.io/cloud-builders/gsutil'
  id: Deploy
  args: ['cp', '-r', 'src/build/*', 'gs://soulution.cloud/']