steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['--cwd', 'src', 'install']
- name: 'gcr.io/cloud-builders/yarn'
  args: ['--cwd', 'src', 'build']
- name: 'gcr.io/cloud-builders/gsutil'
  id: Deploy
  args: ['cp', '-r', 'src/build/*', 'gs://soulution.cloud/']