steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/soulution', '.']
  volumes:
  - name: 'build'
    path: '/app/build'
- name: 'gcr.io/cloud-builders/gsutil'
  id: Deploy
  args: ['cp', '-r', 'src/build/*', 'gs://soulution.cloud/']
  volumes:
  - name: 'build'
    path: '/app/build'